name: Build Check

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
jobs:
  setup-build-test:
    runs-on: ubuntu-latest  

    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true
          components: rustfmt
          # cache: cargo

      - name: Build the application
        run: cargo build --release --manifest-path ./src/WebApi/Cargo.toml

  container-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build and Run Docker Compose for Healthcheck Test
        run: docker compose -f ./docker-compose.yml up nginx --wait

      - name: Dump container logs on failure
        if: failure()
        run: docker compose -f ./docker-compose.yml logs db

      - name: Test Healthcheck Endpoint
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9999/healthz)
          if [ "$STATUS" -eq 200 ]; then
            echo "Healthcheck passed with status $STATUS"
          else
            echo "Healthcheck failed with status $STATUS"
            exit 1
          fi
